INSERT INTO subject
  (id, name)
VALUES
  ( 1	, 'Advanced Drawing')	,
  ( 2	, 'Andragogy ' 	)	,
  ( 3	, 'Advanced Graphic Design'	)	,
  ( 4	, 'Advanced Painting'	)	,
  ( 5	, 'Advanced Photography'	)	,
  ( 6	, 'Algebra'	)	,
  ( 7	, 'Anthropology'	)	,
  ( 8	, 'Arab Culture and Islamic Studies'	)	,
  ( 9	, 'Arabie'	)	,
  ( 10	, 'Archaeology'	)	,
  ( 11	, 'Bengali'	)	,
  ( 12	, 'Biology'	)	,
  ( 13	, 'Calculus'	)	,
  ( 14	, 'Ceramics'	)	,
  ( 15	, 'Chemistry'	)	,
  ( 16	, 'Chinese'	)	,
  ( 17	, 'Commerce'	)	,
  ( 18	, 'Comparative Literature'	)	,
  ( 19	, 'Comparative Study of Religions'	)	,
  ( 20	, 'Computer Science and Applications'	)	,
  ( 21	, 'Conceptual Chemistry'	)	,
  ( 22	, 'Criminology'	)	,
  ( 23	, 'Dance'	)	,
  ( 24	, 'Data Structures'	)	,
  ( 25	, 'Defence and Strategic Studies'	)	,
  ( 26	, 'Dogri'	)	,
  ( 27	, 'Drama / Theatre'	)	,
  ( 28	, 'Drawing'	)	,
  ( 29	, 'Economics'	)	,
  ( 30	, 'Education'	)	,
  ( 31	, 'Electronic Science'	)	,
  ( 32	, 'English'	)	,
  ( 33	, 'Environmental Science'	)	,
  ( 34	, 'Folk Literature'	)	,
  ( 35	, 'French'	)	,
  ( 36	, 'Functions, Statistics & Trigonometry'	)	,
  ( 37	, 'Geography'	)	,
  ( 38	, 'Geometry'	)	,
  ( 39	, 'German'	)	,
  ( 40	, 'Graphic Design'	)	,
  ( 41	, 'Gujarati'	)	,
  ( 42	, 'Hindi'	)	,
  ( 43	, 'History'	)	,
  ( 44	, 'Home Science'	)	,
  ( 45	, 'Human Anatomy & Physiology'	)	,
  ( 46	, 'Indian Culture'	)	,
  ( 47	, 'Japanese'	)	,
  ( 48	, 'Kannada'	)	,
  ( 49	, 'Karnatik Music(Vocal Instrument, Percussion)'	)	,
  ( 50	, 'Law'	)	,
  ( 51	, 'Linguistics'	)	,
  ( 52	, 'Maithili'	)	,
  ( 53	, 'Malayalam'	)	,
  ( 54	, 'Management'	)	,
  ( 55	, 'Marathi'	)	,
  ( 56	, 'Mass Communication and Journalism'	)	,
  ( 57	, 'Math'	)	,
  ( 58	, 'Microbiology'	)	,
  ( 59	, 'Museology & Conservation'	)	,
  ( 60	, 'Odia'	)	,
  ( 61	, 'Organic Chemistry'	)	,
  ( 62	, 'Painting'	)	,
  ( 63	, 'Percussion Instruments'	)	,
  ( 64	, 'Persian'	)	,
  ( 65	, 'Philosophy'	)	,
  ( 66	, 'Photography'	)	,
  ( 67	, 'Physical Education'	)	,
  ( 68	, 'Physics'	)	,
  ( 69	, 'Political Science'	)	,
  ( 70	, 'Population Studies'	)	,
  ( 71	, 'Psychology'	)	,
  ( 72	, 'Public Administration'	)	,
  ( 73	, 'Punjabi'	)	,
  ( 74	, 'Rajasthani'	)	,
  ( 75	, 'Russian'	)	,
  ( 76	, 'Sanskrit'	)	,
  ( 77	, 'Social Work'	)	,
  ( 78	, 'Sociology'	)	,
  ( 79	, 'Spanish'	)	,
  ( 80	, 'Statistics AP'	)	,
  ( 81	, 'Tamil'	)	,
  ( 82	, 'Telugu'	)	,
  ( 83	, 'Tribal and Regional Language / Literature'	)	,
  ( 84	, 'Trigonometry'	)	,
  ( 85	, 'Urdu'	)	,
  ( 86	, 'Visual Art'	)	,
  ( 87	, 'Women Studies'	)	;